analyzer:
  skip_excluded: true
excludes:
  scopes:
  - pattern: "build-dependencies"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages only required during build"
  - pattern: "dev-dependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages required for testing"
  paths:
  - pattern: "doc/**"
    reason: "DOCUMENTATION_OF"
    comment: "Not in release artifacts"
  - pattern: "kuksa-val-server/**"
    reason: "OTHER"
    comment: "Not part of databroker. Not in release artifact"
  - pattern: "kuksa_apps/**"
    reason: "OTHER"
    comment: "Not part of databroker. Not in release artifact"
  - pattern: "kuksa_go_client/**"
    reason: "OTHER"
    comment: "Not part of databroker. Not in release artifact"
  - pattern: "test/**"
    reason: "OTHER"
    comment: "Not part of databroker. Not in release artifact"
  - pattern: "kuksa_databroker/integration_test/**"
    reason: "TEST_TOOL_OF"
    comment: "Test only"
license_choices:
  repository_license_choices:
  - given: "OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later"
    choice: "BSD-3-Clause"
  - given: "OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only"
    choice: "BSD-3-Clause"
  - given: "(Apache-2.0 OR MS-PL) AND MIT"
    choice: "Apache-2.0 AND MIT"
  - given: "Apache-2.0 AND (Apache-2.0 OR MS-PL) AND MIT"
    choice: "Apache-2.0 AND MIT"
  - given: "(Apache-2.0 AND MIT) OR (MIT AND MS-PL)"
    choice: "Apache-2.0 AND MIT"
  - given: "(Apache-2.0 AND MIT) OR (Apache-2.0 AND MIT AND MS-PL)"
    choice: "Apache-2.0 AND MIT"
curations:
  packages:
    - id: "Crate::windows"
      curations:
        comment: >-
          License information as per https://crates.io/crates/windows
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::windows_aarch64_msvc"
      curations:
        comment: >-
          License information as per https://crates.io/crates/windows
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::windows_i686_msvc"
      curations:
        comment: >-
          License information as per https://crates.io/crates/windows
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::windows_x86_64_msvc"
      curations:
        comment: >-
          License information as per https://crates.io/crates/windows
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::rand_core"
      curations:
        comment: >-
          License information as per https://crates.io/crates/rand_core
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::nix"
      curations:
        comment: >-
          License information as per https://crates.io/crates/nix
        concluded_license: "MIT"
    - id: "Crate::ureq"
      curations:
        comment: >-
          License information as per https://crates.io/crates/ureq
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::web-sys"
      curations:
        comment: >-
          License information as per https://crates.io/crates/web-sys
        concluded_license: "MIT OR Apache-2.0"
    - id: "Crate::ryu"
      curations:
        comment: >-
          License information as per https://crates.io/crates/ryu
        concluded_license: "Apache-2.0 OR BSL-1.0"
    - id: "Crate::num-bigint"
      curations:
        comment: >-
          License information as per https://crates.io/crates/num-bigint . Scanned and approved https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11390
        concluded_license: "MIT OR Apache-2.0"
#resolutions:
#  rule_violations:
#  - message: "License MPL-2.0 found for statically linked package 'Crate::webpki-roots:"
#    reason: "CANT_FIX_EXCEPTION"
#    comment: "This is only pulled in during build, by the ureq crate; as soon as the above scope exclusion works this resolution can be removed."
