
name: Extract from OCI image
description: Can copy files out of an OCI image

inputs:
  plattform:
    required: true
    type: choice
    description: Choose platform, e.g. linux/arm64
    options:
      - linux/arm64
      - linux/amd64
      - linux/riscv64
    image:
      required: true
      type: string
      description: The OCI image
    src:
      required: true
      type: string
      description: Path inside container
    dest:
      required: true
      type: string
      description: Path in workspace
    export:
      required: false
      default: false
      description: Archive dest and export as Actiona artifact
      

runs:
  using: "composite"
  steps:
    - shell: bash
      run: | 
        mkdir -p ${{ inputs.dest }}
        docker rm TESTID || true
        docker create --name TESTID --platform  ${{ inputs.platform }}  ${{ inputs.image }}
        docker cp TESTID:${{ inputs.src }} ${{ inputs.dest }}  
        docker rm TESTID
        ls -ahl ${{ inputs.dest }}
        
     - if: inputs.export == 'true'
       run: | 
         tar -czf ${{ inputs.dest }}.tar.gz -C ${{ inputs.dest }} . 
       
      
  
