name: spdx

on:
  pull_request

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # required to grab the history of the PR
        fetch-depth: 0

    - name: Get changed files
      run: |
        echo "files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} | tr '\n' ',')" >> $GITHUB_ENV
        
    - name: Check SPDX Licenses
      run: |
        chmod u+x .github/workflows/verify-spdx-headers
        echo "export INPUT_FILES="${{ env.files }}""| echo "export INPUT_LICENSES="Apache 2.0 MIT"" | xargs .github/workflows/verify-spdx-headers
      shell: bash
